Repository wecode-bootcamp-korea/22-2nd-Oneted-frontend, pull requests merged in 2021-07, with the labels that each got.

#5 [Add] login 레이아웃 + 모달 레이아웃
  package-lock.json
  public/images/kakao_login_large_wide.png
  public/index.html
  src/components/Modal/LoginModal.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
Labels: Status: Accepted

#4 [22기 최창원] 기본 컴포넌트 구조 레이아웃 완료
  public/data/postListData.json
  src/pages/Main/Main.js
  src/pages/Main/PostList/PostCard/PostCard.js
  src/pages/Main/PostList/PostList.js
  src/styles/theme.js
Labels: Status: 수정 요청

#10 [22기 최창원] 메인화면에 들어갈 정렬 버튼 레이아웃 및 기본함수 구현 했습니다.
  src/pages/Main/Main.js
  src/pages/Main/OrderBy/OrderBy.js
Labels: Status: Accepted

#8 [22기 박관용] git 충돌 해결 + pdf 파일 다운로드 기능 추가
  package-lock.json
  package.json
  src/Routes.js
  src/index.js
  src/pages/Resume/Resume.js
  src/pages/Resume/ResumeForm.js
  src/styles/theme.js
Labels: Status: Accepted, Status: 수정 요청

#7 [22기 박관용] git 충돌해결 + 코드리뷰 반영
  public/index.html
  src/Routes.js
  src/components/Modal/LoginModal.js
  src/components/Modal/Modal.js
  src/components/Modal/SearchListModal.js
  src/components/Modal/SearchModal.js
  src/components/Modal/TagModal.js
  src/components/Nav/Nav.js
  src/index.js
  src/pages/SearchResult/SearchResult.js
Labels: Status: Accepted, Status: 수정 요청

#12 [22기 최창원] 메인 직업 필터링 레이아웃 작성
  src/pages/Main/Main.js
  src/pages/Main/MainJobCategori/MainJobCategori.js
Labels: Status: 수정 요청

#13 [22기 박관용] 피드백 반영
  src/Routes.js
  src/components/Modal/LoginModal.js
  src/components/Modal/SearchListModal.js
  src/components/Modal/SearchModal.js
  src/components/Modal/TagModal.js
  src/components/Nav/Nav.js
  src/config.js
Labels: Status: Accepted

#14 [22기 최창원]지원 현황 레이아웃 작성
  src/pages/Application/Application.js
  src/pages/Main/Main.js
  src/styles/theme.js
Labels: Status: 수정 요청

#9 [22기 최창원] 모달 필터 기능 구현 및 레이아웃 완성(리팩토링 완료)
  src/pages/Main/FilterButton/FilterButton.js
  src/pages/Main/FilterButton/FilterModal/FilterModal.js
  src/pages/Main/Main.js
  src/pages/Main/OrderBy/OrderBy.js
  src/pages/Main/PostList/PostCard/PostCard.js
  src/pages/Main/PostList/PostList.js
Labels: Status: 리뷰 요청

#6 [22기 최민재] 리뷰 반영, Conflict 해결 완료
  public/data/data.json
  public/data/jobData.json
  public/images/icon_checkbox.svg
  public/images/icon_share.svg
  public/index.html
  src/pages/Detail/Detail.js
  src/pages/Detail/Modal/ModalApply.js
  src/pages/Detail/Modal/ModalBookmark.js
  src/pages/Detail/Modal/ModalShare.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#11 [22기 최창원] 라이브러리 활용한 메인 페이지 슬라이드 구현
  package-lock.json
  package.json
  public/images/slide1.jpg
  public/images/slide2.jpg
  public/images/slide3.jpg
  src/Routes.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlider/MainSlider.js
Labels: Status: Accepted

#15 [22기 최창원] 지역 선택을 위한 모달 셀렉트 옵션 버튼 레이아웃 입니다.
  src/pages/Main/Main.js
  src/pages/Main/RegionButton/RegionButton.js
  src/pages/Main/RegionButton/RegionModal/RegionModal.js
  src/styles/Text.js
Labels: Status: 리뷰 요청

#16 [22기 박관용] conflit 해결, 코드 리팩토링
  src/Routes.js
  src/pages/Resume/Resume.js
  src/pages/Resume/ResumeButton.js
  src/pages/Resume/ResumeForm.js
Labels: Status: 리뷰 요청

#17 [22기 박관용] 디바운스 useRef 사용, rebase 충돌 해결
  src/Routes.js
  src/components/Modal/SearchListModal.js
  src/components/Modal/SearchModal.js
  src/config.js
  src/pages/Main/PostList/PostCard/PostCard.js
  src/pages/Main/PostList/PostList.js
  src/pages/SearchResult/SearchResult.js
Labels: Status: 리뷰 요청

#18 [22기 최민재] 리뷰 반영 작업
  src/Routes.js
  src/index.js
  src/pages/Detail/Modal/ModalApply/ModalApply.js
  src/pages/Detail/Modal/ModalApply/UploadFileList/UploadFileList.js
  src/styles/theme.js
Labels: Status: Accepted

#20 [22기 박관용] chart.js 라이브러리를 활용한 직군별 연봉차트 구현
  package-lock.json
  package.json
  src/Routes.js
  src/pages/Salary/ChartData.js
  src/pages/Salary/Salary.js
Labels: Status: 리뷰 요청

#23 [22기 박관용] fix브랜치 ( 완성된 기능들 병합)
  src/Routes.js
  src/components/Modal/LoginModal.js
  src/components/Modal/SearchListModal.js
  src/components/Modal/SearchModal.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Modal/ModalApply.js
  src/pages/Detail/Modal/ModalApply/ModalApply.js
  src/pages/Detail/Modal/ModalApply/UploadFileList/UploadFileList.js
  src/pages/Main/Main.js
  src/pages/Main/PostList/PostList.js
  src/pages/Resume/Resume.js
  src/pages/Resume/ResumeButton.js
  src/pages/Resume/ResumeForm.js
  src/pages/Salary/Salary.js
  src/pages/SearchResult/SearchResult.js
Labels: Status: 추가 기능 구현중

#24 [22기 최창원] 이력서 현황 페이지
  src/components/Modal/LoginModal.js
  src/pages/Application/Application.js
  src/pages/Application/PostList/PostList.js
  src/pages/Main/Main.js
Labels: Status: 추가 기능 구현중

#25 [22기 박관용] 마이페이지 추가
  src/Routes.js
  src/components/Nav/Nav.js
  src/pages/Application/Application.js
  src/pages/Application/PostList/PostCard/PostCard.js
  src/pages/Application/PostList/PostList.js
  src/pages/Detail/Modal/ModalApply/ModalApply.js
Labels: Status: 리뷰 요청
